[package]
name = "rkfs"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
panic = "abort"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
